pipeline {
    agent any
    environment {
        myuser = "maheshpoojaryneu"
        docker_password = credentials('DOCKER_CRED')
    }
    triggers {
        githubPush() // Trigger the job on a GitHub push event
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    changelog: false,
                    credentialsId: 'GH_CRED',
                    poll: false,
                    url: 'https://github.com/cyse7125-su24-team11/static-site.git'
            }
        }
        stage('Docker') {
            steps {
                script {
                    try {
                        sh '''
                        echo ${docker_password} | docker login --username ${myuser} --password-stdin
                        docker build -f ./Dockerfile -t webapp:latest  .
                        docker tag webapp:latest maheshpoojaryneu/csye7125:webapp
                        docker push maheshpoojaryneu/csye7125:webapp
                        '''
                    } catch (Exception e) {
                        throw e
                    }
                }
            }
        }
    }
}
